language: python
postgres:
    adapter: postgresql
    database: makahiki
    username: postgres
env:
    - DATABASE_URL=postgres://postgres@127.0.0.1:5432/makahiki
install: pip install -r requirements.txt --use-mirrors
script: python makahiki/manage.py test
after_script:
    - cd makahiki;
    - scripts/run_pylint.sh
    - scripts/run_pep8.sh

